inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
   - 'db:schema.rb'
   - 'bin/*'
   - 'config/**/*'
   - 'vendor/**/*'
   - 'node_modules/**/*' 
  Rails:
    Enabled: true